# Generated by Django 5.0.14 on 2025-06-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFESOR', '0002_alter_profesor_especializacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('seccion', models.CharField(choices=[('M', 'Matutina'), ('V', 'Vespertina')], max_length=1)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
