# Generated by Django 5.0.14 on 2025-06-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFESOR', '0003_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='perido',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
