# Generated by Django 5.0.14 on 2025-06-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROFESOR', '0004_curso_perido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='perido',
            new_name='periodo',
        ),
    ]
