# Generated by Django 5.0.14 on 2025-06-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFESOR', '0005_rename_perido_curso_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
