# Generated by Django 5.0.14 on 2025-06-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0008_reporte_somnolencias_reporte_tiempos_distraccion_and_more'),
        ('PROFESOR', '0006_curso_fecha_final_curso_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='niños',
            field=models.ManyToManyField(related_name='cursos', to='NIÑO.niño'),
        ),
    ]
