# Generated by Django 5.0.14 on 2025-06-11 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFESOR', '0007_curso_niños'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PROFESOR.profesor'),
        ),
    ]
