# Generated by Django 5.0.14 on 2025-06-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0007_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='somnolencias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tiempos_distraccion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tiempos_somnolencia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='distracciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='duracion_evaluacion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
