# Generated by Django 5.0.14 on 2025-06-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0007_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoNiño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_desbloqueado', models.IntegerField(default=1)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tiempo_total', models.IntegerField(default=0)),
                ('niño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='NIÑO.niño')),
            ],
        ),
    ]
