# Generated by Django 5.0.14 on 2025-06-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0008_progresoniño'),
        ('NIÑO', '0008_reporte_somnolencias_reporte_tiempos_distraccion_and_more'),
    ]

    operations = [
    ]
