# Generated by Django 5.0.14 on 2025-06-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0009_merge_20250609_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='distracciones',
            field=models.IntegerField(blank=True, help_text='Cantidad de distracciones detectadas', null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='duracion_evaluacion',
            field=models.DurationField(blank=True, help_text='Duración total de la evaluación', null=True),
        ),
    ]
