# Generated by Django 5.0.14 on 2025-06-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0010_alter_reporte_distracciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoCartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_desbloqueado', models.IntegerField(default=1)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('tiempo_total', models.IntegerField(default=0)),
                ('niño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NIÑO.niño')),
            ],
        ),
    ]
