# Generated by Django 5.0.14 on 2025-06-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0011_progresocartas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='frames_distraccion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='frames_somnolencia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
